"use client";

import { useCallback, useEffect, useState } from "react";
import { X } from "lucide-react";

type Review = { id: string; payload: { nombre?: string; empresa?: string; email?: string }; reason: string; created_at: string };

export function ImportReviewDialog({ onClose, onNotice }: { onClose: () => void; onNotice: (message: string) => void }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/import/reviews"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setReviews(data.reviews); } catch (error) { onNotice(error instanceof Error ? error.message : "No se han podido cargar las revisiones."); } finally { setLoading(false); } }, [onNotice]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function resolve(id: string, decision: "create" | "skip") { setBusy(id); try { const response = await fetch("/api/import/reviews", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, decision }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setReviews((current) => current.filter((review) => review.id !== id)); onNotice(decision === "create" ? "Cliente creado tras la revisión." : "Duplicado descartado."); } catch (error) { onNotice(error instanceof Error ? error.message : "No se ha podido resolver la revisión."); } finally { setBusy(null); } }
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-black/70 p-4"><div className="mx-auto my-8 w-full max-w-2xl rounded-xl border border-line bg-surface-raised p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-accent">CONTROL DE IMPORTACIÓN</p><h2 className="mt-1 text-xl font-semibold">Posibles duplicados de clientes</h2><p className="mt-2 text-sm text-muted">Decide si crear el cliente o descartar la fila antes de cerrar la revisión.</p></div><button aria-label="Cerrar revisiones" onClick={onClose} className="rounded-md p-1 text-muted hover:bg-surface-hover"><X className="size-5" /></button></div><div className="mt-6 space-y-3">{loading ? <p className="text-sm text-muted">Cargando revisiones…</p> : reviews.length ? reviews.map((review) => <article key={review.id} className="rounded-lg border border-line bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{review.payload.nombre || "Cliente sin nombre"}</p><p className="mt-1 text-sm text-muted">{review.payload.empresa || "Sin empresa"}{review.payload.email ? ` · ${review.payload.email}` : ""}</p><p className="mt-2 text-xs text-[#f8d870]">{review.reason}</p></div><div className="flex gap-2"><button disabled={busy === review.id} onClick={() => void resolve(review.id, "skip")} className="rounded-lg border border-line px-3 py-2 text-xs font-semibold text-muted disabled:opacity-50">Descartar</button><button disabled={busy === review.id} onClick={() => void resolve(review.id, "create")} className="rounded-lg bg-accent px-3 py-2 text-xs font-bold text-accent-foreground disabled:opacity-50">Crear cliente</button></div></div></article>) : <p className="rounded-lg border border-line bg-surface p-4 text-sm text-muted">No hay duplicados pendientes de revisión.</p>}</div></div></div>;
}
